<#
.SYNOPSIS
    Regenerates MarketExtension/Properties/Resources.Designer.cs from Resources.resx.

.DESCRIPTION
    A CLI stand-in for Visual Studio's PublicResXFileCodeGenerator custom tool. VS regenerates the
    Designer automatically when you save the .resx, so you normally never need this. Use it only when
    you edit Resources.resx WITHOUT Visual Studio (a text editor, a script, etc.) — `dotnet build` does
    NOT run the VS generator, so the Designer would otherwise go stale.

    It mirrors System.Resources.Tools.StronglyTypedResourceBuilder: one `public static string <Key>`
    property per <data> entry, keys sorted ordinally, XML-escaped doc comments — i.e. the same output
    VS produces, so a later VS save yields a near-zero diff.

    Always commit the regenerated Resources.Designer.cs alongside the .resx.

.EXAMPLE
    pwsh tools/gen-resources.ps1
#>
[CmdletBinding()]
param(
    [string]$Resx,
    [string]$Out
)

$ErrorActionPreference = 'Stop'

$repoRoot = Split-Path $PSScriptRoot -Parent
if (-not $Resx) { $Resx = Join-Path $repoRoot 'MarketExtension\Properties\Resources.resx' }
if (-not $Out)  { $Out  = Join-Path $repoRoot 'MarketExtension\Properties\Resources.Designer.cs' }

if (-not (Test-Path $Resx)) { throw "resx not found: $Resx" }

[xml]$doc = Get-Content -Raw -Path $Resx

# string resources only (skip any entry that declares a 'type' or 'mimetype' — those are non-strings)
$data = $doc.root.data | Where-Object { -not $_.type -and -not $_.mimetype }

# StronglyTypedResourceBuilder emits properties sorted ordinal-ascending by name
$map = [ordered]@{}
foreach ($n in $data) { $map[$n.name] = $n }
$names = [string[]]@($map.Keys)
[Array]::Sort($names, [System.StringComparer]::Ordinal)

$nl = "`r`n"
$sb = [System.Text.StringBuilder]::new()

$header = @'
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketExtension.Properties {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MarketExtension.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
'@
[void]$sb.Append($header).Append($nl)

foreach ($key in $names) {
    $val = [string]$map[$key].value
    # collapse newlines for the doc comment, then XML-escape (< > & ' ")
    $val = $val -replace "`r`n", ' ' -replace "`n", ' ' -replace "`r", ' '
    $esc = [System.Security.SecurityElement]::Escape($val)
    [void]$sb.Append('        ').Append($nl)
    [void]$sb.Append('        /// <summary>').Append($nl)
    [void]$sb.Append('        ///   Looks up a localized string similar to ').Append($esc).Append('.').Append($nl)
    [void]$sb.Append('        /// </summary>').Append($nl)
    [void]$sb.Append('        public static string ').Append($key).Append(' {').Append($nl)
    [void]$sb.Append('            get {').Append($nl)
    [void]$sb.Append('                return ResourceManager.GetString("').Append($key).Append('", resourceCulture);').Append($nl)
    [void]$sb.Append('            }').Append($nl)
    [void]$sb.Append('        }').Append($nl)
}

[void]$sb.Append('    }').Append($nl)
[void]$sb.Append('}').Append($nl)

# UTF-8 WITH BOM — matches what Visual Studio writes for generated Designer files
$enc = [System.Text.UTF8Encoding]::new($true)
[System.IO.File]::WriteAllText($Out, $sb.ToString(), $enc)
Write-Host "Wrote $($names.Count) properties to $Out"
