//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketExtension.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MarketExtension.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Action_Open {
            get {
                return ResourceManager.GetString("Action_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read article.
        /// </summary>
        public static string Action_ReadArticle {
            get {
                return ResourceManager.GetString("Action_ReadArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Action_Refresh {
            get {
                return ResourceManager.GetString("Action_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Action_Search {
            get {
                return ResourceManager.GetString("Action_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View details.
        /// </summary>
        public static string Action_ViewDetails {
            get {
                return ResourceManager.GetString("Action_ViewDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Elbstream.
        /// </summary>
        public static string Attribution_OpenName {
            get {
                return ResourceManager.GetString("Attribution_OpenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo images via elbstream.com.
        /// </summary>
        public static string Attribution_Subtitle {
            get {
                return ResourceManager.GetString("Attribution_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logos provided by Elbstream.
        /// </summary>
        public static string Attribution_Title {
            get {
                return ResourceManager.GetString("Attribution_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading {0} chart….
        /// </summary>
        public static string Chart_Loading {
            get {
                return ResourceManager.GetString("Chart_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No chart data for this range..
        /// </summary>
        public static string Chart_NoData {
            get {
                return ResourceManager.GetString("Chart_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Favorites.
        /// </summary>
        public static string Cmd_AddToFavorites {
            get {
                return ResourceManager.GetString("Cmd_AddToFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Watchlist.
        /// </summary>
        public static string Cmd_AddToWatchlist {
            get {
                return ResourceManager.GetString("Cmd_AddToWatchlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from Favorites.
        /// </summary>
        public static string Cmd_RemoveFromFavorites {
            get {
                return ResourceManager.GetString("Cmd_RemoveFromFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from Portfolio.
        /// </summary>
        public static string Cmd_RemoveFromPortfolio {
            get {
                return ResourceManager.GetString("Cmd_RemoveFromPortfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from Watchlist.
        /// </summary>
        public static string Cmd_RemoveFromWatchlist {
            get {
                return ResourceManager.GetString("Cmd_RemoveFromWatchlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markets.
        /// </summary>
        public static string Command_Markets {
            get {
                return ResourceManager.GetString("Command_Markets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markets - News.
        /// </summary>
        public static string Command_MarketsNews {
            get {
                return ResourceManager.GetString("Command_MarketsNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markets Portfolio.
        /// </summary>
        public static string Command_MarketsPortfolio {
            get {
                return ResourceManager.GetString("Command_MarketsPortfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Australian Dollar (AUD).
        /// </summary>
        public static string Currency_AUD {
            get {
                return ResourceManager.GetString("Currency_AUD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brazilian Real (BRL).
        /// </summary>
        public static string Currency_BRL {
            get {
                return ResourceManager.GetString("Currency_BRL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canadian Dollar (CAD).
        /// </summary>
        public static string Currency_CAD {
            get {
                return ResourceManager.GetString("Currency_CAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swiss Franc (CHF).
        /// </summary>
        public static string Currency_CHF {
            get {
                return ResourceManager.GetString("Currency_CHF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese Yuan (CNY).
        /// </summary>
        public static string Currency_CNY {
            get {
                return ResourceManager.GetString("Currency_CNY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danish Krone (DKK).
        /// </summary>
        public static string Currency_DKK {
            get {
                return ResourceManager.GetString("Currency_DKK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Euro (EUR).
        /// </summary>
        public static string Currency_EUR {
            get {
                return ResourceManager.GetString("Currency_EUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to British Pound (GBP).
        /// </summary>
        public static string Currency_GBP {
            get {
                return ResourceManager.GetString("Currency_GBP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hong Kong Dollar (HKD).
        /// </summary>
        public static string Currency_HKD {
            get {
                return ResourceManager.GetString("Currency_HKD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indian Rupee (INR).
        /// </summary>
        public static string Currency_INR {
            get {
                return ResourceManager.GetString("Currency_INR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japanese Yen (JPY).
        /// </summary>
        public static string Currency_JPY {
            get {
                return ResourceManager.GetString("Currency_JPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South Korean Won (KRW).
        /// </summary>
        public static string Currency_KRW {
            get {
                return ResourceManager.GetString("Currency_KRW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mexican Peso (MXN).
        /// </summary>
        public static string Currency_MXN {
            get {
                return ResourceManager.GetString("Currency_MXN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Norwegian Krone (NOK).
        /// </summary>
        public static string Currency_NOK {
            get {
                return ResourceManager.GetString("Currency_NOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Zealand Dollar (NZD).
        /// </summary>
        public static string Currency_NZD {
            get {
                return ResourceManager.GetString("Currency_NZD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polish Złoty (PLN).
        /// </summary>
        public static string Currency_PLN {
            get {
                return ResourceManager.GetString("Currency_PLN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swedish Krona (SEK).
        /// </summary>
        public static string Currency_SEK {
            get {
                return ResourceManager.GetString("Currency_SEK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Singapore Dollar (SGD).
        /// </summary>
        public static string Currency_SGD {
            get {
                return ResourceManager.GetString("Currency_SGD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to US Dollar (USD).
        /// </summary>
        public static string Currency_USD {
            get {
                return ResourceManager.GetString("Currency_USD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South African Rand (ZAR).
        /// </summary>
        public static string Currency_ZAR {
            get {
                return ResourceManager.GetString("Currency_ZAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open {0}.
        /// </summary>
        public static string DataAttribution_OpenName {
            get {
                return ResourceManager.GetString("DataAttribution_OpenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quotes may be delayed or inaccurate.
        /// </summary>
        public static string DataAttribution_Subtitle {
            get {
                return ResourceManager.GetString("DataAttribution_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data provided by {0}.
        /// </summary>
        public static string DataAttribution_Title {
            get {
                return ResourceManager.GetString("DataAttribution_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markets Extension for Command Palette.
        /// </summary>
        public static string Extension_DisplayName {
            get {
                return ResourceManager.GetString("Extension_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open an instrument and star it from its detail page.
        /// </summary>
        public static string Favorites_Empty_Subtitle {
            get {
                return ResourceManager.GetString("Favorites_Empty_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No favorites yet.
        /// </summary>
        public static string Favorites_Empty_Title {
            get {
                return ResourceManager.GetString("Favorites_Empty_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter favorites....
        /// </summary>
        public static string Favorites_Placeholder {
            get {
                return ResourceManager.GetString("Favorites_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search, Watchlist, Favorites....
        /// </summary>
        public static string Hub_Placeholder {
            get {
                return ResourceManager.GetString("Hub_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ★ Favorite · Enter for details.
        /// </summary>
        public static string Membership_Favorite {
            get {
                return ResourceManager.GetString("Membership_Favorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter for details.
        /// </summary>
        public static string Membership_None {
            get {
                return ResourceManager.GetString("Membership_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On watchlist · Enter for details.
        /// </summary>
        public static string Membership_Watchlist {
            get {
                return ResourceManager.GetString("Membership_Watchlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On watchlist · ★ Favorite · Enter for details.
        /// </summary>
        public static string Membership_WatchlistFavorite {
            get {
                return ResourceManager.GetString("Membership_WatchlistFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Sources.
        /// </summary>
        public static string Nav_DataSources_Title {
            get {
                return ResourceManager.GetString("Nav_DataSources_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starred instruments, shown on the dock.
        /// </summary>
        public static string Nav_Favorites_Subtitle {
            get {
                return ResourceManager.GetString("Nav_Favorites_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites.
        /// </summary>
        public static string Nav_Favorites_Title {
            get {
                return ResourceManager.GetString("Nav_Favorites_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string Nav_News_Title {
            get {
                return ResourceManager.GetString("Nav_News_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portfolio.
        /// </summary>
        public static string Nav_Portfolio_Title {
            get {
                return ResourceManager.GetString("Nav_Portfolio_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Look up a stock, crypto, or currency.
        /// </summary>
        public static string Nav_Search_Subtitle {
            get {
                return ResourceManager.GetString("Nav_Search_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Nav_Search_Title {
            get {
                return ResourceManager.GetString("Nav_Search_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Nav_Settings_Title {
            get {
                return ResourceManager.GetString("Nav_Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instruments you track.
        /// </summary>
        public static string Nav_Watchlist_Subtitle {
            get {
                return ResourceManager.GetString("Nav_Watchlist_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watchlist.
        /// </summary>
        public static string Nav_Watchlist_Title {
            get {
                return ResourceManager.GetString("Nav_Watchlist_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string News_Category_All {
            get {
                return ResourceManager.GetString("News_Category_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s no market news to show right now..
        /// </summary>
        public static string News_Empty_Subtitle {
            get {
                return ResourceManager.GetString("News_Empty_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No headlines.
        /// </summary>
        public static string News_Empty_Title {
            get {
                return ResourceManager.GetString("News_Empty_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter headlines.
        /// </summary>
        public static string News_Placeholder {
            get {
                return ResourceManager.GetString("News_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}d ago.
        /// </summary>
        public static string News_Time_DaysAgo {
            get {
                return ResourceManager.GetString("News_Time_DaysAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}h ago.
        /// </summary>
        public static string News_Time_HoursAgo {
            get {
                return ResourceManager.GetString("News_Time_HoursAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to just now.
        /// </summary>
        public static string News_Time_JustNow {
            get {
                return ResourceManager.GetString("News_Time_JustNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}m ago.
        /// </summary>
        public static string News_Time_MinutesAgo {
            get {
                return ResourceManager.GetString("News_Time_MinutesAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Sources.
        /// </summary>
        public static string Page_DataSources_Title {
            get {
                return ResourceManager.GetString("Page_DataSources_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markets Favorites.
        /// </summary>
        public static string Page_Favorites_Title {
            get {
                return ResourceManager.GetString("Page_Favorites_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markets.
        /// </summary>
        public static string Page_Markets_Title {
            get {
                return ResourceManager.GetString("Page_Markets_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markets Portfolio.
        /// </summary>
        public static string Page_Portfolio_Title {
            get {
                return ResourceManager.GetString("Page_Portfolio_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markets Search.
        /// </summary>
        public static string Page_Search_Title {
            get {
                return ResourceManager.GetString("Page_Search_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markets Watchlist.
        /// </summary>
        public static string Page_Watchlist_Title {
            get {
                return ResourceManager.GetString("Page_Watchlist_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add holdings from an instrument&apos;s detail page.
        /// </summary>
        public static string Portfolio_Empty_Subtitle {
            get {
                return ResourceManager.GetString("Portfolio_Empty_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No holdings yet.
        /// </summary>
        public static string Portfolio_Empty_Title {
            get {
                return ResourceManager.GetString("Portfolio_Empty_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter holdings....
        /// </summary>
        public static string Portfolio_Placeholder {
            get {
                return ResourceManager.GetString("Portfolio_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total {0}.
        /// </summary>
        public static string Portfolio_Row_TotalReturnPrefix {
            get {
                return ResourceManager.GetString("Portfolio_Row_TotalReturnPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portfolio {0}.
        /// </summary>
        public static string Portfolio_TotalsRow_Title {
            get {
                return ResourceManager.GetString("Portfolio_TotalsRow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will refresh automatically once the limit clears..
        /// </summary>
        public static string RateLimit_Subtitle {
            get {
                return ResourceManager.GetString("RateLimit_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate-limited.
        /// </summary>
        public static string RateLimit_Tag {
            get {
                return ResourceManager.GetString("RateLimit_Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate-limited — showing last known prices.
        /// </summary>
        public static string RateLimit_Title {
            get {
                return ResourceManager.GetString("RateLimit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requests are being throttled — prices may be stale.
        /// </summary>
        public static string RateLimit_Tooltip {
            get {
                return ResourceManager.GetString("RateLimit_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter to search.
        /// </summary>
        public static string Search_Action_Subtitle {
            get {
                return ResourceManager.GetString("Search_Action_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search markets for &quot;{0}&quot;.
        /// </summary>
        public static string Search_Action_Title {
            get {
                return ResourceManager.GetString("Search_Action_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No matches for &quot;{0}&quot;.
        /// </summary>
        public static string Search_NoMatches {
            get {
                return ResourceManager.GetString("Search_NoMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by symbol or name, then Enter.
        /// </summary>
        public static string Search_Placeholder {
            get {
                return ResourceManager.GetString("Search_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search results.
        /// </summary>
        public static string Search_ResultsSection {
            get {
                return ResourceManager.GetString("Search_ResultsSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crypto.
        /// </summary>
        public static string Section_Crypto {
            get {
                return ResourceManager.GetString("Section_Crypto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string Section_Currency {
            get {
                return ResourceManager.GetString("Section_Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Section_Other {
            get {
                return ResourceManager.GetString("Section_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stocks.
        /// </summary>
        public static string Section_Stocks {
            get {
                return ResourceManager.GetString("Section_Stocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  at {0}/unit.
        /// </summary>
        public static string SetQty_BasisNote {
            get {
                return ResourceManager.GetString("SetQty_BasisNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average cost per unit (optional).
        /// </summary>
        public static string SetQty_Card_CostBasis {
            get {
                return ResourceManager.GetString("SetQty_Card_CostBasis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average price you paid, in the instrument&apos;s currency. Leave 0 if unknown..
        /// </summary>
        public static string SetQty_Card_Help {
            get {
                return ResourceManager.GetString("SetQty_Card_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity held.
        /// </summary>
        public static string SetQty_Card_Quantity {
            get {
                return ResourceManager.GetString("SetQty_Card_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a quantity greater than 0.
        /// </summary>
        public static string SetQty_Card_QuantityError {
            get {
                return ResourceManager.GetString("SetQty_Card_QuantityError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SetQty_Card_Save {
            get {
                return ResourceManager.GetString("SetQty_Card_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a number greater than 0..
        /// </summary>
        public static string SetQty_Error_Number {
            get {
                return ResourceManager.GetString("SetQty_Error_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity must be greater than 0. To remove a holding, use Remove from Portfolio..
        /// </summary>
        public static string SetQty_Error_Positive {
            get {
                return ResourceManager.GetString("SetQty_Error_Positive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Portfolio.
        /// </summary>
        public static string SetQty_Name_Add {
            get {
                return ResourceManager.GetString("SetQty_Name_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit holding.
        /// </summary>
        public static string SetQty_Name_Edit {
            get {
                return ResourceManager.GetString("SetQty_Name_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add {0} to portfolio.
        /// </summary>
        public static string SetQty_Title_Add {
            get {
                return ResourceManager.GetString("SetQty_Title_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit {0} holding.
        /// </summary>
        public static string SetQty_Title_Edit {
            get {
                return ResourceManager.GetString("SetQty_Title_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set {0} to {1}{2}.
        /// </summary>
        public static string SetQty_Toast_Set {
            get {
                return ResourceManager.GetString("SetQty_Toast_Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste your API key.
        /// </summary>
        public static string Settings_ApiKey_Placeholder {
            get {
                return ResourceManager.GetString("Settings_ApiKey_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show built-in sample data instead of live prices. Ideal for trying out the extension..
        /// </summary>
        public static string Settings_Demo_Desc {
            get {
                return ResourceManager.GetString("Settings_Demo_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demo mode.
        /// </summary>
        public static string Settings_Demo_Label {
            get {
                return ResourceManager.GetString("Settings_Demo_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finnhub API key..
        /// </summary>
        public static string Settings_Finnhub_Desc {
            get {
                return ResourceManager.GetString("Settings_Finnhub_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finnhub API key.
        /// </summary>
        public static string Settings_Finnhub_Label {
            get {
                return ResourceManager.GetString("Settings_Finnhub_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News refresh interval in minutes (0 = off)..
        /// </summary>
        public static string Settings_NewsRefresh_Desc {
            get {
                return ResourceManager.GetString("Settings_NewsRefresh_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News refresh interval (minutes).
        /// </summary>
        public static string Settings_NewsRefresh_Label {
            get {
                return ResourceManager.GetString("Settings_NewsRefresh_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seconds each set of headlines shows before the dock news ticker advances (default 60)..
        /// </summary>
        public static string Settings_NewsTicker_Desc {
            get {
                return ResourceManager.GetString("Settings_NewsTicker_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News ticker speed (seconds).
        /// </summary>
        public static string Settings_NewsTicker_Label {
            get {
                return ResourceManager.GetString("Settings_NewsTicker_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency for portfolio totals. Other holdings are converted into it..
        /// </summary>
        public static string Settings_PortfolioCurrency_Desc {
            get {
                return ResourceManager.GetString("Settings_PortfolioCurrency_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portfolio currency.
        /// </summary>
        public static string Settings_PortfolioCurrency_Label {
            get {
                return ResourceManager.GetString("Settings_PortfolioCurrency_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show a banner when prices are stale from provider rate-limiting..
        /// </summary>
        public static string Settings_RateLimit_Desc {
            get {
                return ResourceManager.GetString("Settings_RateLimit_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show rate-limit warnings.
        /// </summary>
        public static string Settings_RateLimit_Label {
            get {
                return ResourceManager.GetString("Settings_RateLimit_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price refresh interval in minutes (0 = off)..
        /// </summary>
        public static string Settings_Refresh_Desc {
            get {
                return ResourceManager.GetString("Settings_Refresh_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price refresh interval (minutes).
        /// </summary>
        public static string Settings_Refresh_Label {
            get {
                return ResourceManager.GetString("Settings_Refresh_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twelve Data API key. Used first when set..
        /// </summary>
        public static string Settings_TwelveData_Desc {
            get {
                return ResourceManager.GetString("Settings_TwelveData_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twelve Data API key.
        /// </summary>
        public static string Settings_TwelveData_Label {
            get {
                return ResourceManager.GetString("Settings_TwelveData_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulated prices. Enter to turn off in Settings..
        /// </summary>
        public static string Status_Demo_Subtitle {
            get {
                return ResourceManager.GetString("Status_Demo_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demo mode.
        /// </summary>
        public static string Status_Demo_Tag {
            get {
                return ResourceManager.GetString("Status_Demo_Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demo mode — showing sample data.
        /// </summary>
        public static string Status_Demo_Title {
            get {
                return ResourceManager.GetString("Status_Demo_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing sample data, not live prices.
        /// </summary>
        public static string Status_Demo_Tooltip {
            get {
                return ResourceManager.GetString("Status_Demo_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a Finnhub API key in Settings to load market news..
        /// </summary>
        public static string Status_NewsNoKey_Subtitle {
            get {
                return ResourceManager.GetString("Status_NewsNoKey_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News needs a Finnhub key.
        /// </summary>
        public static string Status_NewsNoKey_Title {
            get {
                return ResourceManager.GetString("Status_NewsNoKey_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market news is provided by Finnhub..
        /// </summary>
        public static string Status_NewsNoKey_Tooltip {
            get {
                return ResourceManager.GetString("Status_NewsNoKey_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter to add one in Settings..
        /// </summary>
        public static string Status_NoKey_Subtitle {
            get {
                return ResourceManager.GetString("Status_NoKey_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action required.
        /// </summary>
        public static string Status_NoKey_Tag {
            get {
                return ResourceManager.GetString("Status_NoKey_Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No API key set.
        /// </summary>
        public static string Status_NoKey_Title {
            get {
                return ResourceManager.GetString("Status_NoKey_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No API key set — functionality is limited.
        /// </summary>
        public static string Status_NoKey_Tooltip {
            get {
                return ResourceManager.GetString("Status_NoKey_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added {0} to favorites.
        /// </summary>
        public static string Toast_AddedToFavorites {
            get {
                return ResourceManager.GetString("Toast_AddedToFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added {0} to watchlist.
        /// </summary>
        public static string Toast_AddedToWatchlist {
            get {
                return ResourceManager.GetString("Toast_AddedToWatchlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t open {0}: {1}.
        /// </summary>
        public static string Toast_OpenUrlFailed {
            get {
                return ResourceManager.GetString("Toast_OpenUrlFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed {0} from favorites.
        /// </summary>
        public static string Toast_RemovedFromFavorites {
            get {
                return ResourceManager.GetString("Toast_RemovedFromFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed {0} from portfolio.
        /// </summary>
        public static string Toast_RemovedFromPortfolio {
            get {
                return ResourceManager.GetString("Toast_RemovedFromPortfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed {0} from watchlist.
        /// </summary>
        public static string Toast_RemovedFromWatchlist {
            get {
                return ResourceManager.GetString("Toast_RemovedFromWatchlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}%) today.
        /// </summary>
        public static string Ui_Portfolio_DailyChange {
            get {
                return ResourceManager.GetString("Ui_Portfolio_DailyChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  · Total {0} ({1}%).
        /// </summary>
        public static string Ui_Portfolio_TotalReturnNote {
            get {
                return ResourceManager.GetString("Ui_Portfolio_TotalReturnNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  · {0} holdings not converted.
        /// </summary>
        public static string Ui_Portfolio_Unconverted_Many {
            get {
                return ResourceManager.GetString("Ui_Portfolio_Unconverted_Many", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  · 1 holding not converted.
        /// </summary>
        public static string Ui_Portfolio_Unconverted_One {
            get {
                return ResourceManager.GetString("Ui_Portfolio_Unconverted_One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sh.
        /// </summary>
        public static string Ui_Position_Unit_Shares {
            get {
                return ResourceManager.GetString("Ui_Position_Unit_Shares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to units.
        /// </summary>
        public static string Ui_Position_Unit_Units {
            get {
                return ResourceManager.GetString("Ui_Position_Unit_Units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open an instrument and add it from its detail page.
        /// </summary>
        public static string Watchlist_Empty_Subtitle {
            get {
                return ResourceManager.GetString("Watchlist_Empty_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your watchlist is empty.
        /// </summary>
        public static string Watchlist_Empty_Title {
            get {
                return ResourceManager.GetString("Watchlist_Empty_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter watchlist....
        /// </summary>
        public static string Watchlist_Placeholder {
            get {
                return ResourceManager.GetString("Watchlist_Placeholder", resourceCulture);
            }
        }
    }
}
